name: native_assets_package
description: "A new Dart FFI package project."
version: 0.0.1

environment:
  sdk: '>=3.5.0-109.0.dev <4.0.0'

dependencies:
  cli_config: ^0.2.0
  logging: ^1.2.0
  native_assets_cli: ^0.5.3
  native_toolchain_c: ^0.4.1

dev_dependencies:
  ffi: ^2.1.0
  ffigen: ^11.0.0
  flutter_lints: ^3.0.0
  test: ^1.24.9
