on:
  pull_request:
  push:
    branches:
      - main

name: Build Test

jobs:
  Main:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest, }
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Install GTK
        if: (matrix.platform.os == 'ubuntu-latest')
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev
      - uses: actions/checkout@v2
      - name: Cache cargo folder
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: cargo-${{ matrix.platform.target }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'master'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: flutter pub get
        working-directory: ./build_test/project1
