on:
  pull_request:
  push:
    branches:
      - main

name: Build Test

jobs:
  Main:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest, }
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Install GTK
        if: (matrix.platform.os == 'ubuntu-latest')
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'master'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: flutter config --enable-windows-desktop
      - run: flutter config --enable-linux-desktop
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
        working-directory: ./build_test/project1
      - run: cargo build --target=${{ matrix.platform.target }}
        working-directory: ./build_test/project1
      - run: cargo build --target=${{ matrix.platform.target }} --release
        working-directory: ./build_test/project1
      - run: cargo build --target=${{ matrix.platform.target }} --release
        working-directory: ./build_test/project1
        env:
          FLUTTER_PROFILE: 1
      - run: flutter pub get
        working-directory: ./build_test/project2
      - run: cargo build --target=${{ matrix.platform.target }}
        working-directory: ./build_test/project2
      - run: cargo build --target=${{ matrix.platform.target }} --release
        working-directory: ./build_test/project2
      - run: cargo build --target=${{ matrix.platform.target }} --release
        working-directory: ./build_test/project2
        env:
          FLUTTER_PROFILE: 1
